# This uses a reusable workflow
name: Reusable Workflow to add a project to issues

on:
  issues:
    types: [opened]

jobs:
  do-it:
    uses: ./.github/workflows/add_project_to_issue_reusable.yml
    secrets:
        PROJECT_URL: "https://github.com/users/${{ secrets.USER }}/projects/${{ secrets.PROJECT_NUMBER }}"
        GH_TOKEN: ${{ secrets.GH_TOKEN }}