# This uses a reusable workflow
name: Reusable Workflow to add a project to issues

on:
  issues:
    types: [opened]

jobs:
  do-it:
    steps:
      uses: ./.github/workflows/add_project_to_issue_reusable.yml
      secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USER: ${{ secrets.USER }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}

      uses: ./.github/workflows/add_assignee_to_issue_reusable.yml
      secrets:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}