# This uses a reusable workflow
name: Reusable Workflow to add a project to issues

on:
  issues:
    types: [opened]

jobs:
  do-it:
    uses: ./.github/workflows/add_project_to_issue_reusable.yml@main
    secrets:
        PROJECT_URL: ${{ secrets.PROJECT_URL }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}